# .github/workflows/deploy.yml
name: CI/CD Pipeline

# 1. main 브랜치에 푸시될 때마다 실행
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 2. 리포지토리 코드 체크아웃
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      # 3. JDK 설치 (Temurin 17)
      - name: JDK 설치
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Gradle 캐시
      - name: Gradle 캐시
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}

      # 4. Gradle 빌드 (테스트 제외)
      - name: 빌드 및 테스트
        run: bash gradlew clean build -x test


      # 5. 빌드된 JAR 파일을 서버로 복사 (scp)
      - name: 서버에 JAR 배포
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          # build/libs 아래에 생성된 JAR 파일 경로 (와일드카드 사용)
          source: "build/libs/progmong.jar"
          target: "/opt/progmong"
          overwrite: true

      # 6. systemd 서비스 재시작
      - name: 서비스 재시작
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart progmong.service
